apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: spring-cloud-task-cronjob
spec:
  schedule: "*/1 * * * *"
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: spring-cloud-task-as-k8s-cronjob
            image: 'rawsanj/spring-cloud-task-as-k8s-cronjob:0.1.2'
            envFrom:
            - configMapRef:
                name: spring-cloud-task-cronjob-config
            - secretRef:
                name: spring-cloud-task-cronjob-secret
            args:
            - /bin/sh
            - -c
            - echo 'Starting Spring Batch Task' && java -jar app.jar
          restartPolicy: OnFailure
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-cloud-task-cronjob-config
data:
  MYSQL_DB_HOST: 'mysql-service'
  MYSQL_DB_PORT: '3306'
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: 'org.hibernate.dialect.MySQL5Dialect'
  API_URL: 'https://bitpay.com/api/rates'

---
apiVersion: v1
kind: Secret
metadata:
  name: spring-cloud-task-cronjob-secret
type: Opaque
data:
  DATABASE_USERNAME: Y3JvbkpvYlVzZXI=
  MYSQL_DATABASE: c3ByaW5nLWJhdGNoLWRi
  DATABASE_PASSWORD: U3VwZXJTZWNyZXRNeXNxbFB3ZA==
  SPRING_MAIL_USERNAME: PEJhc2U2NCBFbmNvZGVkIEVtYWlsIEFkZHJlc3M+
  SPRING_MAIL_PASSWORD: PEJhc2U2NCBFbmNvZGVkIEVtYWlsIFBhc3N3b3JkPg==
